### ISSUE TITLE
Does the MFA code needs to be password?

### ISSUE THREAD

**Issue by ifuyivara** [enderv/awsmfa-go#1]
Nice!

I haven't tried it yet. But does the MFA code needs to be a password? Don't we want the user to see what numbers he has entered in the terminal (and is no secret really) for better UI?

```
mfaArray, err := terminal.ReadPassword(int(syscall.Stdin))
```

maybe can be replaced with 

```
reader := bufio.NewReader(os.Stdin)
mfa, err := reader.ReadString('\n')
```

**Comment by enderv** [comment]
#2 Changing in this PR hope you're happy 😁
